package org.example.myaccountant

enum class UserRole{
    ADMIN, USER
}

enum class ErrorCodes(val code: Long) {

    USERNAME_ALREADY_EXISTS(103),
    USER_NOT_FOUND(104),
    USER_ALREADY_EXISTS(105),
    PASSWORD_IS_INCORRECT(106),
    NOT_LOGGED_IN_EXCEPTION(107),
    PHONE_NUMBER_ALREADY_EXISTS(108),

    CATEGORY_ALREADY_EXISTS(203),
    CATEGORY_NOT_FOUND(204),
    CATEGORY_NAME_ALREADY_EXISTS(205),


}

